- name: Install and Configure WebServer
  hosts: aws_ec2
  become: yes  # Use sudo for privileges elevation
  vars:
    welcome_message: "<h1>Welcome to ACS730 PROJECT!</h1><h2>My private IP is {{ ansible_default_ipv4.address }}</h2><h2>Built by Sarvesh Nagar using Ansible!</h2><img src='https://finalproject-sarvesh.s3.us-east-1.amazonaws.com/Sarvesharch.png' alt='Prject Architecture'>"

  tasks:
    - name: Update all packages to their latest version
      yum:
        name: "*"
        state: latest

    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: Create index.html with custom welcome message
      copy:
        dest: /var/www/html/index.html
        content: "{{ welcome_message }}"
        owner: apache
        group: apache
        mode: '0644'

    - name: Ensure httpd is started and enabled on boot
      systemd:
        name: httpd
        state: started
        enabled: yes